# Generated by Django 4.1.4 on 2022-12-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogador', models.CharField(max_length=30)),
                ('nome_personagem', models.CharField(max_length=30)),
                ('raca', models.CharField(max_length=30)),
                ('classe', models.CharField(max_length=30)),
                ('arquetipo', models.CharField(default='', max_length=30)),
                ('nivel', models.IntegerField(default=1)),
                ('antecedente', models.CharField(max_length=15)),
                ('tendencia', models.CharField(max_length=30)),
                ('divindade', models.CharField(default='', max_length=30)),
                ('terra_natal', models.CharField(default='', max_length=30)),
                ('forca', models.IntegerField(default=1)),
                ('destreza', models.IntegerField(default=1)),
                ('constituicao', models.IntegerField(default=1)),
                ('inteligencia', models.IntegerField(default=1)),
                ('sabedoria', models.IntegerField(default=1)),
                ('carisma', models.IntegerField(default=1)),
            ],
        ),
    ]
