# Generated by Django 4.1.4 on 2022-12-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichapersonagem',
            name='c_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichapersonagem',
            name='deslocamento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichapersonagem',
            name='iniciativa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichapersonagem',
            name='inspiracao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichapersonagem',
            name='proficiencia',
            field=models.IntegerField(default=0),
        ),
    ]
