# Generated by Django 4.1.4 on 2022-12-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0002_fichapersonagem_c_a_fichapersonagem_deslocamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichapersonagem',
            name='dados_vida',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichapersonagem',
            name='pv_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichapersonagem',
            name='pv_maximo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichapersonagem',
            name='res_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichapersonagem',
            name='res_cons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichapersonagem',
            name='res_des',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichapersonagem',
            name='res_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichapersonagem',
            name='res_sab',
            field=models.IntegerField(default=0),
        ),
    ]
