# Generated by Django 4.1.4 on 2022-12-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0004_fichapersonagem_res_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichapersonagem',
            name='res_car',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='fichapersonagem',
            name='res_cons',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='fichapersonagem',
            name='res_des',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='fichapersonagem',
            name='res_int',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='fichapersonagem',
            name='res_sab',
            field=models.BooleanField(default='False'),
        ),
    ]
