# Generated by Django 4.1.4 on 2022-12-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0006_periciaspersonagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichapersonagem',
            name='acrobacia',
            field=models.BooleanField(default='False'),
        ),
        migrations.DeleteModel(
            name='PericiasPersonagem',
        ),
    ]
