# Generated by Django 4.1.4 on 2022-12-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0008_fichapersonagem_adestrar_animais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogador', models.CharField(max_length=30)),
                ('nome_personagem', models.CharField(max_length=30)),
                ('raca', models.CharField(max_length=30)),
                ('classe', models.CharField(max_length=30)),
                ('arquetipo', models.CharField(default='', max_length=30)),
                ('nivel', models.IntegerField(default=1)),
                ('antecedente', models.CharField(max_length=15)),
                ('tendencia', models.CharField(max_length=30)),
                ('divindade', models.CharField(default='', max_length=30)),
                ('terra_natal', models.CharField(default='', max_length=30)),
                ('iniciativa', models.IntegerField(default=0)),
                ('c_a', models.IntegerField(default=0)),
                ('deslocamento', models.IntegerField(default=0)),
                ('inspiracao', models.IntegerField(default=0)),
                ('proficiencia', models.IntegerField(default=0)),
                ('pv_maximo', models.IntegerField(default=0)),
                ('pv_atual', models.IntegerField(default=0)),
                ('dados_vida', models.IntegerField(default=0)),
                ('idiomas', models.CharField(default='Comum', max_length=120)),
                ('forca', models.IntegerField(default=1)),
                ('destreza', models.IntegerField(default=1)),
                ('constituicao', models.IntegerField(default=1)),
                ('inteligencia', models.IntegerField(default=1)),
                ('sabedoria', models.IntegerField(default=1)),
                ('carisma', models.IntegerField(default=1)),
                ('res_for', models.BooleanField(default='False')),
                ('res_des', models.BooleanField(default='False')),
                ('res_cons', models.BooleanField(default='False')),
                ('res_int', models.BooleanField(default='False')),
                ('res_sab', models.BooleanField(default='False')),
                ('res_car', models.BooleanField(default='False')),
                ('acrobacia', models.BooleanField(default='False')),
                ('adestrar_animais', models.BooleanField(default='False')),
                ('arcanismo', models.BooleanField(default='False')),
                ('atletismo', models.BooleanField(default='False')),
                ('atuacao', models.BooleanField(default='False')),
                ('enganacao', models.BooleanField(default='False')),
                ('furtividade', models.BooleanField(default='False')),
                ('historia', models.BooleanField(default='False')),
                ('intimidacao', models.BooleanField(default='False')),
                ('intuicao', models.BooleanField(default='False')),
                ('investigação', models.BooleanField(default='False')),
                ('medicina', models.BooleanField(default='False')),
                ('natureza', models.BooleanField(default='False')),
                ('percepcao', models.BooleanField(default='False')),
                ('persuasao', models.BooleanField(default='False')),
                ('prestidigitar', models.BooleanField(default='False')),
                ('religiao', models.BooleanField(default='False')),
                ('sobrevivencia', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadesClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talento', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=999)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagem.basepersonagem')),
            ],
        ),
        migrations.DeleteModel(
            name='FichaPersonagem',
        ),
    ]
