# Generated by Django 4.1.4 on 2022-12-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0009_basepersonagem_habilidadesclasse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepersonagem',
            name='res_for',
            field=models.BooleanField(default=False),
        ),
    ]
