# Generated by Django 4.1.4 on 2022-12-16 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0010_alter_basepersonagem_res_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidadesclasse',
            old_name='talento',
            new_name='habilidade',
        ),
        migrations.CreateModel(
            name='TalentosClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talento', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=999)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagem.basepersonagem')),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicasRaciaisClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=999)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagem.basepersonagem')),
            ],
        ),
    ]
