# Generated by Django 4.1.4 on 2022-12-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0011_rename_talento_habilidadesclasse_habilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepersonagem',
            name='ores_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basepersonagem',
            name='ores_cons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basepersonagem',
            name='ores_des',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basepersonagem',
            name='ores_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basepersonagem',
            name='ores_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basepersonagem',
            name='ores_sab',
            field=models.IntegerField(default=0),
        ),
    ]
