# Generated by Django 4.1.4 on 2022-12-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0014_alter_basepersonagem_tendencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepersonagem',
            name='carisma',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='constituicao',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='destreza',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='forca',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='inteligencia',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ores_cons',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ores_des',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ores_for',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ores_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ores_sab',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_acrobacia',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_adestrar_animais',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_arcanismo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_atletismo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_atuacao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_enganacao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_furtividade',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_historia',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_intimidacao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_intuicao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_investigação',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_medicina',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_natureza',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_percepcao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_persuasao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_prestidigitar',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_religiao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ot_sobrevivencia',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='sabedoria',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
