# Generated by Django 4.1.4 on 2022-12-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0015_alter_basepersonagem_carisma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepersonagem',
            name='arcanismo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
