# Generated by Django 4.1.4 on 2022-12-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0016_alter_basepersonagem_arcanismo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepersonagem',
            name='atletismo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
