# Generated by Django 4.1.4 on 2022-12-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0017_alter_basepersonagem_atletismo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepersonagem',
            name='acrobacia',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='adestrar_animais',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='atuacao',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='enganacao',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='furtividade',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='historia',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='intimidacao',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='intuicao',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='investigação',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='medicina',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='natureza',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='ores_car',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='percepcao',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='persuasao',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='prestidigitar',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='religiao',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='res_car',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='res_cons',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='res_des',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='res_for',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='res_int',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='res_sab',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basepersonagem',
            name='sobrevivencia',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
