# Generated by Django 4.1.4 on 2023-02-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personagem", "0003_magiaspersonagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="magiaspersonagem",
            name="duraçao",
        ),
        migrations.AddField(
            model_name="magiaspersonagem",
            name="duracao",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AlterField(
            model_name="magiaspersonagem",
            name="alcance",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="magiaspersonagem",
            name="componentes",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="magiaspersonagem",
            name="descricao",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="magiaspersonagem",
            name="nivel",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="magiaspersonagem",
            name="nome",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="magiaspersonagem",
            name="tempo_conjuracao",
            field=models.CharField(default="", max_length=50),
        ),
    ]
