# Generated by Django 4.1.4 on 2023-02-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personagem", "0004_remove_magiaspersonagem_duraçao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="magiaspersonagem",
            name="escola",
            field=models.CharField(default="", max_length=25),
        ),
    ]
