# Generated by Django 4.1.4 on 2023-03-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personagem", "0006_remove_basepersonagem_ores_car_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventariopersonagem",
            name="item_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
