# Generated by Django 4.1.4 on 2022-12-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoAventura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.IntegerField(default=0)),
                ('moeda', models.CharField(choices=[('pc', 'Cobre'), ('pp', 'Prata'), ('pe', 'Electro'), ('po', 'Ouro'), ('pl', 'Platina')], max_length=2)),
                ('peso', models.FloatField(blank=True, default=0, null=True)),
                ('descricao', models.TextField(blank=True, default='', null=True)),
                ('propriedades', models.TextField(blank=True, default='', null=True)),
                ('habilidade', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
