# Generated by Django 4.1.4 on 2023-02-28 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personagem", "0006_remove_basepersonagem_ores_car_and_more"),
        ("itens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BolsaDeMoedas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pc", models.IntegerField(default=0)),
                ("pp", models.IntegerField(default=0)),
                ("pe", models.IntegerField(default=0)),
                ("po", models.IntegerField(default=0)),
                ("pl", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ItemBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("preco", models.IntegerField(default=0)),
                (
                    "moeda",
                    models.CharField(
                        choices=[
                            ("pc", "Cobre"),
                            ("pp", "Prata"),
                            ("pe", "Electro"),
                            ("po", "Ouro"),
                            ("pl", "Platina"),
                        ],
                        max_length=2,
                    ),
                ),
                ("peso", models.FloatField(blank=True, default=0, null=True)),
                ("descricao", models.TextField(blank=True, default="", null=True)),
                (
                    "personagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personagem.basepersonagem",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="EquipamentoAventura",
            new_name="ItemsComuns",
        ),
        migrations.CreateModel(
            name="Armaduras",
            fields=[
                (
                    "itembase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="itens.itembase",
                    ),
                ),
                ("ca", models.IntegerField(default=0)),
                ("forca", models.IntegerField(default=0)),
                ("furtividade", models.BooleanField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("AL", "Armadura Leve"),
                            ("AM", "Armadura Média"),
                            ("AP", "Armadura Pesada"),
                            ("E", "Escudo"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            bases=("itens.itembase",),
        ),
        migrations.CreateModel(
            name="Armas",
            fields=[
                (
                    "itembase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="itens.itembase",
                    ),
                ),
                ("dano", models.CharField(max_length=30)),
                ("propriedades", models.TextField(blank=True, default="")),
            ],
            bases=("itens.itembase",),
        ),
    ]
