# Generated by Django 4.1.4 on 2023-02-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itens", "0002_bolsademoedas_itembase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itembase",
            name="fonte",
            field=models.CharField(blank=True, default="", max_length=128, null=True),
        ),
    ]
